sudo: required
services:
      - docker
language: go
go:
- 1.7.1
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - DEV_REPO=stephenrlouie/travis-dev
    - PROD_REPO=stephenrlouie/travis-prod
script:
  - make test
  - make

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - echo $TRAVIS_TAG
  - docker build -f Dockerfile -t $DEV_REPO:$COMMIT .
  - test $TRAVIS_BRANCH == "master" \
    && docker tag $DEV_REPO:$COMMIT $PROD_REPO:latest
  - test $TRAVIS_TAG != "" \
    && docker tag $DEV_REPO:$COMMIT $PROD_REPO:$TRAVIS_TAG
  - docker push $REPO

notifications:
  slack:
    rooms:
      - $SLACK_TOKEN
    on_success: always
    on_failure: always
  email: false
