sudo: required
services:
      - docker
language: go
go:
- 1.7.1
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
script:
  - make test
  - make

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "stephenrlouie/travis-prod"; else echo "stephenrlouie/travis-dev" ; fi`
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $COMMIT ; fi`
  - echo $TRAVIS_TAG
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO

notifications:
  slack:
    rooms:
      - $SLACK_TOKEN
    on_success: always
    on_failure: always
  email: false
