sudo: required
services:
      - docker
language: go
go:
- 1.7.1
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - DEV_REPO=stephenrlouie/travis-dev
    - PROD_REPO=stephenrlouie/travis-prod
script:
  - make test
  - make container
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t $DEV_REPO:$COMMIT .
  - docker push $DEV_REPO
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then docker tag $DEV_REPO:$COMMIT $PROD_REPO:latest && docker push $PROD_REPO; fi
  - if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DEV_REPO:$COMMIT $PROD_REPO:$TRAVIS_TAG && docker push $PROD_REPO; fi
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then docker tag $DEV_REPO:$COMMIT $DEV_REPO:cron && docker push $DEV_REPO; fi
notifications:
  slack:
    rooms:
      - $SLACK_TOKEN
    on_success: always
    on_failure: always
  email: false
